#!/bin/bash
#sysctl net.ipv4.ip_forward=1
#iptables -t nat -A PREROUTING -p tcp --dport 25565 -j DNAT --to-destination 94.250.254.176:25565
#iptables -t nat -A POSTROUTING -j MASQUERADE
#ifconfig em1:4 149.154.68.33 netmask 255.255.254.0 up
#iptables -A PREROUTING -t nat -p tcp -d 149.154.68.33 --dport 25565 -j DNAT --to-destination 94.250.254.176:25565
#iptables -A POSTROUTING -t nat -p tcp -d 94.250.254.176 --dport 25565 -j SNAT --to-source 149.154.68.33:25565
